version: '3.4'
services:
  lunch-bot:
    image: lunch-bot
    container_name: lunch-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TOKEN=${TOKEN}
    restart: always
