version: "3"
services:
  app:
    container_name: hko-lunch-bot
    build: .
    environment:
      - EXAMPLE_TOKEN=1332942054:AAFrASzNpBqrCoiVzTGn65YKCQ7prHEvz98
      - EXAMPLE_CONTROLLER_ID=-400962750
    restart: always
    network_mode: bridge
