version: '3.4'
services:
  tglunchbot:
    image: tglunchbot
    container_name: hko-lunch-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TOKEN=${TOKEN}
    restart: always
