version: "3"
services:
  app:
    container_name: hko-lunch-bot
    build: .
    environment:
      - MSG_TIME=12:15
      - TOKEN=1332942054:AAFrASzNpBqrCoiVzTGn65YKCQ7prHEvz98
      - CHAT_ID=-1001210702490
    restart: always
    network_mode: bridge
